name: HelloWorld
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Verifying the Docker
      run: docker version
    - name: Docker Login
      run: docker login -u badri.vaikunth@gmail.com -p Srihari@2025
