name: HelloWorld
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Verifying the Docker
      run: docker version
    - name: Docker Login
      env:
        DOCKER_USERNAME: badri.vaikunth@gmail.com
        DOCKER_PASSWORD: Srihari@2025
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Printing UN
      run: echo $DOCKER_USERNAME
    - name: Printing PWD
      run: echo $DOCKER_PASSWORD
