name: HelloWorld
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Verifying the Docker
      run: docker version
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u $DOCKER_USERNAME --password-stdin
    - name: Printing UN
      run: echo $DOCKER_USERNAME
    - name: Printing PWD
      run: echo $DOCKER_PASSWORD
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Printing UN
      run: echo $DOCKER_USERNAME
    - name: Printing PWD
      run: echo ${{secrets.DOCKER_PASSWORD}}
