name: HelloWorld
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Verifying the Docker
      run: docker version
    - name: Docker Login
      env:
        USERNAME: badri.vaikunth@gmail.com
        PASSWORD: Srihari@2025
      run: docker login -u $USERNAME -p $PASSWORD
