name: HelloWorld
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Pulling the Code
      uses: actions/checkout@v4
    - name: Present Working Directory
      run: echo pwd    
    - name: Verify Java Code Availability
      run: cat helloworld.java
    - name: Upload the helloworld java file
      uses: actions/upload-artifact@v4
      with:
        name: javacode
        path: helloworld.java
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Download the helloworld java file
      uses: actions/download-artifact@v4
      with:
        name: javacode
        path: helloworld.java
    - name: Read the HelloWorld
      run: cat helloworld.java
