name: HelloWorld
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Pulling the Code
      uses: actions/checkout@v4
    - name: Present Working Directory
      run: echo pwd    
    - name: Verify Java Code Availability
      run: cat helloworld.java
    - name: which chromedriver
      run: which chromedriver
    - name: Execute Cypress Shellscript
      run: |
        chmod +x cypress.sh 
        ./cypress.sh
