name: TestJOb
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Print HelloWorld1
      run: echo "HelloWorld1"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Print HelloWorld2
      run: echo "HelloWorld2"
